### ISSUE TITLE
Request for Code

### ISSUE THREAD

**Issue by akhilkedia** [SHUMKASHUN/FIRST#1]
Hi!
Congratulations on the EMNLP paper. The paper said the code will be available at this URL, however it appears that the code has not been released yet. Could you release the code?

**Comment by SHUMKASHUN** [comment]
@akhilkedia Thanks for the interest in our work. Sorry for the late post, I forget to push the codebase. I am releasing the code now. Please take a look and you can @ me if you encounter any problems.
